 .MODEL SMALL
.STACK
.DATA
TITULO DB 10, 13, 7, "CONVERSOR DE DECIMAL A HEXADECIMAL","$"
INGRESAR DB 10,13,7,"INGRESA UN NUMERO DECIMAL MENOR O IGUAL A 255: ","$"
RESULTADO DB 10,13,7,"EL RESULTADO EN HEXADECIMAL ES: ", "$"
SALTO DB 10,13,7,"$"  

D1 DB 0
D2 DB 0
D3 DB 0
D4 DB 0
D5 DB 0
D6 DB 0
D7 DB 0
D8 DB 0
D9 DB 0
D10 DB 0
D11 DB 0
D12 DB 0
D13 DB 0
D14 DB 0
D15 DB 0
D16 DB 0
C DD 0  ;ALMACENAR LAS DECENAS
D DB 0  ;ALMACENAR DECENAS
U DB 0  ;ALMACENAR LAS UNIDADES
NUMERO DD 0;PARA ALMACENAR EL NUMERO COMPLETO
N DB 0 ; ALMACENA EL NUMERO MENOR A 255  
AUXI DB 0; AUXILIAR
AUXI2 DB 0; AUXILIAR
AUXI3 DB 0; AUXILIAR


.CODE 

    MOV AX,@DATA  ;TRANSFERIR LOS DATOS AL REGISTRO AX
    MOV DS, AX   ; SE TRANSFIEREN LOS DATOS DEL REGISTRO AX AL DX
    MOV AH,09H   ; FUNCIONA PARA IMPRIMIR EL MENSAJE EN PANTALLA
    LEA DX,TITULO ; CARGA EL MENSAJE DE TITULO 
    INT 21H ;INTERRUPCION 
 
   
                              
 
   DECHEXA:    ; ETIQUETA QUE CONTIENE CONVERSION DE DECIMAL A HEXADECIMAL
   MOV AH,09H     ;METODO PRA IMPRESION EN PANTALLA
   LEA DX,INGRESAR; CARGA EL MENSAJE INGRESAR
   INT 21H        ;INTERRUPCION
   CALL DECIMALES ; LLAMA AL PROCEDIMENTO DECIMALES
   XOR DX,DX
   MOV AX,0      ;0 A AX
   MOV AX,NUMERO ; TRANSFIERE NUMERO A AX
   CMP AX,255    ; COMPARA EL NUMERO LEIDO CON 255
   JBE MENOR2    ; 
   JA SALIR
   
   
   
   MENOR2:
   MOV N,AL          ; SE PASA AL A N
   MOV BL,16         ; SE TRANSFIERE 16 A BL
   CALL HEXA          ; SE LLAMA AL PROC HEXA
   MOV AH,AUXI3      ; SE TRANSFIERE EL VALOR DE AUXI A AH 
   MOV D1,AH         ;SE PASA AH A D1
   MOV N,AL          ; SE PASA AL A N
   CMP N,0           ;SE COMPARA N CON 0 
   JE IMPRIMIRH 
   CALL HEXA     ; SI ES 0 IMPRIME EL NUMERO TAL CUAL ES
   MOV AH, AUXI3     ; SE TRANSFIERE AUXI 3 A AH 
   MOV D2,AH         ; MOV D2 
   MOV N, AL         ; SE TRANSFIERE AL A N 
   CMP N,0           ; SE COMPARA AL CON N
    ;SEPARACION
   JE IMPRIMIRH       ; SALTA A IMPRIMIR 
   JMP IMPRIMIRH      ; SALTA A IMPRIMIR EN AMBOS CASOS
   
   HEXA PROC      ;INICIO PROCEDIMIENTO HEXADECIMAL
    DIV BL        ; SE DIVIDE BL
    MOV AUXI3,AH  ; SE PASA EL RESIDUO A D1 
    MOV N,0       ; SE COLOCA   EN N
    MOV N,AL      ; SE TRANSFIERE AL A  N
    RET           ; RETORNO
    HEXA ENDP     ; FIN DEL PROCESO HEXA
   
   IMPRIMIRH:
   MOV AH,09H
   LEA DX,RESULTADO
   INT 21H
   
   CMP D2,10
   JE AGREGARA3
   CMP D2,11
   JE AGREGARB3
   CMP D2,12
   JE AGREGARC3
   CMP D2,13
   JE AGREGARD3
   CMP D2,14
   JE AGREGARE3
   CMP D2,15
   JE AGREGARF3
   JMP IMH3
    
   AGREGARA3:
   MOV D2,11H ; COLOCA 11H EN D2
   MOV AH,02H ;FUNCION PARA SALIDA DE CARACTER
   MOV Dl,D2  ; SE TRANSFIERE D2 A DL 
   ADD Dl,30H ; SE SUMA 30 H A DL PARA OBTENER EL NUMERO EN ACCI
   INT 21H    ;INTERRUMPE 21H
   JMP H4     ; SALTA A EL SIGUIENTE DIGITO
   AGREGARB3:
   MOV D2,12H
   MOV AH,02H
   MOV Dl,D2
   ADD Dl,30H
   INT 21H
   JMP H4
   AGREGARC3:
   MOV D2,13H
   MOV AH,02H
   MOV Dl,D2
   ADD Dl,30H
   INT 21H
   JMP H4
   AGREGARD3:
   MOV D2,14H
   MOV AH,02H
   MOV Dl,D2
   ADD Dl,30H
   INT 21H
   JMP H4
   AGREGARE3:
   MOV D2,15H
   MOV AH,02H
   MOV Dl,D2
   ADD Dl,30H
   INT 21H
   JMP H4
   AGREGARF3:
   MOV D2,16H
   MOV AH,02H
   MOV Dl,D2
   ADD Dl,30H
   INT 21H
   JMP H4   
   
   IMH3:
   MOV AH,02H
   MOV Dl, D2
   ADD Dl,30H
   INT 21H
   JMP H4 
   
   H4:
   CMP D1,10
   JE AGREGARA4
   CMP D1,11
   JE AGREGARB4
   CMP D1,12
   JE AGREGARC4
   CMP D1,13
   JE AGREGARD4
   CMP D1,14
   JE AGREGARE4
   CMP D1,15
   JE AGREGARF4
   JMP IMH4
    
   AGREGARA4:
   MOV D2,11H
   MOV AH,02H
   MOV Dl,D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR
   AGREGARB4:
   MOV D2,12H
   MOV AH,02H
   MOV Dl,D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR
   AGREGARC4:
   MOV D2,13H
   MOV AH,02H
   MOV Dl,D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR
   AGREGARD4:
   MOV D2,14H
   MOV AH,02H
   MOV Dl,D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR
   AGREGARE4:
   MOV D2,15H
   MOV AH,02H
   MOV Dl,D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR
   AGREGARF4:
   MOV D2,16H
   MOV AH,02H
   MOV Dl,D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR   
   
   IMH4:
   MOV AH,02H
   MOV Dl, D1
   ADD Dl,30H
   INT 21H
   JMP LIMPIAR 
   

     
   DECIMALES PROC  ;PROC DECIMALES  INICIO
   MOV AH,01H      ;FUNCION PARA CAPTURAR
   INT 21H         ;INTERRUPCION
   SUB AX,130H     ;RESTAR AL REGISTRO AX 130 
   MOV C, AX       ;SE TRANSFIERE EL CONTENIDO DEL REGISTRO AL A D1
   MOV AH, 01H
   INT 21H 
   SUB AX,130H
   MOV D,AL        ;SE TRANSFIERE EL CONTENIDO DEL REGISTRO AL A D2
   MOV AH,01H
   INT 21H
   SUB AL,30H   ; SE RESTA AL REGISTRO AL 30H
   MOV U,AL      ;SE TRANSFIERE EL CONTENIDO DEL REGISTRO AL A D3
 
 MULTIPC:
     XOR AX,AX ;OR EXCLUSIVO PARA VALIDAR ENTRADA VERDADERA 
     CMP C,0    ;COMPARA A C CON 0
     JZ MULTIPD ; SI ES 0 SALTA A MULTPD 
     MOV AX,00  ; SE TRANSFIERE 00 AL REGISTRO AX
     MOV AX,C   ; SE TRANSFIERE LAS CENTENAS AL REGISTRO AX
     MOV BX,100 ; SE TRANSFIERE 100 AL REGISTRO BX
     MUL BX     ; SE HACE LA MULTIPLICACION AX=BX*AX
     MOV C,0    ;SE COLOCA 0 EN C
     MOV C,AX   ; SE TRANSFIERE EL RESULTADO DE AX A C
     
 MULTIPD:
     XOR AX,AX
     CMP D,0
     JZ ARMAR
     MOV AX,00
     MOV AL,D
     MOV BL,10
     MUL BL
     MOV D,0
     MOV D,AL
     
 ARMAR:
     XOR AX,AX
     MOV AX,C  ; SE TRANSFIERE C A AX
     ADD NUMERO,AX ; SE SUMA AX A NUMERO 
     MOV AX,0      ; 0 EN AX
     MOV AL,D      ;D SE TRANSFIERE A AL         
     ADD NUMERO,AX ;SE SUMA AX A NUMERO
     MOV AX,0      ; 0 EN AX
     MOV AL,U      ; SE TRANSFIERE AX A 0
     ADD NUMERO,AX  ; SE SUMA AX A NUMERO
     
  RET  ; RETORNO
 DECIMALES ENDP ;FIN DEL PROCESO DECIMALES
   
   LIMPIAR:
   MOV AH,09H
   LEA DX, SALTO
   INT 21H
   MOV AX,0
   MOV BX,0
   MOV CX,0
   XOR DX,DX
   XOR CX,CX
   MOV NUMERO,0
   MOV N,0
   MOV AUXI,0
   MOV AUXI2,0
   JMP DECHEXA: 
   
  SALIR:
   MOV AX,4C00H
   INT 21H
   END
   



