  include 'emu8086.inc'
  
   DATA SEGMENT   
          
    MENSAJE DB " ACTIVADOR DE MODOS DE VIDEO  $"
    MSG01 DB "         -------------MENU-----------...$"
    MSG02 DB "    1.- TEXTO 40 x 25...$"
    MSG03 DB "    2.- TEXTO 80 x 25...$"
    MSG04 DB "    3.- MODO GRAFICO...$"
    MSG05 DB "    4.- SALIR...$"
    MSG06 DB "    SELECCIONA LA OPCION:  $"               
    MSG07 DB "PRESIONA CUALQUIER TECLA PARA SALIR...$" 
    MSG08 DB " TEXTO 40 X 25 $"
    MSG081 DB " TEXTO 80 X 25 $" 
    MSG09 DB " MODO GRAFICO $" 
    MENSAJE4 DB "ESCRIBE UNA CADENA:  $"
    MSG0 DB "    COLORES $"
    MSG1 DB "    1.- AZUL $"
    MSG2 DB "    2.- VERDE $ "
    MSG3 DB "    3.- CYAN $"
    MSG4 DB "    4.- ROJO $"
    MSG5 DB "    5.- MAGENTA $"
    MSG6 DB "    6.- CAFE $"
    MSG7 DB "    7.- GRIS CLARO $"
    MSG8 DB "    8.- GRIS OSCURO $"
    MSG9 DB "    9.- AZUL CLARO $"
    MSG10 DB "   0.-VERDE CLARO $" 
    MSG11 DB "    LA CADENA ES:  $"
    
    RESPUESTA DB 40 DUP(' '),'$' 
    RESPUESTA2 DB 40 DUP(' '),'$'   
    RESPUESTA3 DB 40,0,50 DUP('$')    
 ENDS 
                    
  STACK SEGMENT
   DW 128 DUP(0)  
   
  ENDS
  
CODE segment 
    
  START : 
 
   MOV AX,DATA
   MOV DS,AX
   MOV ES,AX
     
 MENU PROC   
    
   MOV AH,0FH
   INT 10H
   MOV AH,0 
   INT 10H
 ;INTERLINEADO
   printn "" 
   ;PIMER MENSAJE 
   MOV AH,09H
   LEA DX, MENSAJE
   INT 21H  
           
   printn ""
   
   ;SEGUNDO MENSAJE 
   MOV AH,09H
   LEA DX, MSG01
   INT 21H
   
   ;INTERLINEADO
    printn ""
  
   ; TERCER MENSAJE
   MOV AH, 09H
   LEA DX, MSG02
   INT 21H   
      
   ;INTERLINEADO
    printn ""
 
   ;CUARTO MENSAJE
   MOV AH, 09H
   LEA DX, MSG03
   INT 21H  
   
   ;INTERLINEADO
    printn ""  
       
   ;QUINTO MENSAJE
   MOV AH, 09H
   LEA DX, MSG04
   INT 21H 
   
   ;INTERLINEADO
    printn ""
       
   ;SEXTO MENSAJE
   MOV AH, 09H
   LEA DX, MSG05
   INT 21H 
           
   ;INTERLINEADO
    printn "" 
    printn ""       
           
   ;SEPTIMO MENSAJE
   MOV AH, 09H
   LEA DX, MSG06
   INT 21H
   
   ;LEER EL TECLADO 

    MOV AH,01
    INT 21H
    SUB AL,30H
    MOV RESPUESTA, AL
    
   ;VERIFICANDO OPCION
   
    CMP RESPUESTA, 1            
    JE CALL TEXTOUNO
   
    CMP RESPUESTA, 2
    JE CALL TEXTODOS
     
    CMP RESPUESTA, 3
    JE CALL MODOGRA
    
    CMP RESPUESTA ,4 
    JE CALL SALIR
  
   
   MENU ENDP  
 
 
   TEXTOUNO: 
       
   PRINTN ""
   PRINTN ""
    MOV AL,00H
    MOV AH,0
    INT 10H
   
   PRINTN ""
   PRINTN ""
   MOV AH, 09H
   LEA DX, MSG08
   INT 21H          
          
   CALL MENUCOLORS1 
   CALL CMPRESPCOLOROPC1  
   
    
   RET    
   
   TEXTODOS: 
    
   
   PRINTN ""
   PRINTN "" 
   MOV AL,03H
    MOV AH,0
    INT 10H
   
   PRINTN ""
   PRINTN "" 
     
   MOV AH, 09H
   LEA DX, MSG081
   INT 21H
   
   CALL MENUCOLORS1
   CALL CMPRESPCOLOROPC2 
   
   
   RET 
               
 
   MODOGRA:  
   
   PRINTN ""
   PRINTN ""
    
    MOV AL,13H
    MOV AH,0
    INT 10H    
   
   PRINTN ""
   PRINTN ""
   MOV AH, 09H
   LEA DX, MSG09
   INT 21H  
    
   CALL MENUCOLORS1  
   
   CALL CMPRESPCOLOROPC3
   
   
   RET
   
   
   SALIR:
   PRINTN ""  
      MOV AH, 09H
      LEA DX, MSG07
      INT 21H
      MOV AH,0H
      INT 16H
      MOV AX,4C00H
      INT 21H
      RET 
          
       
MENUCOLORS1:
   
   PRINTN ""
   PRINTN ""  
   
   MOV AH, 09H
   LEA DX, MSG0
   INT 21H 
    
   PRINTN ""
   
   
   MOV AH, 09H
   LEA DX, MSG1
   INT 21H 
      PRINTN ""

   MOV AH, 09H
   LEA DX, MSG2
   INT 21H  
     
      PRINTN ""
   MOV AH, 09H
   LEA DX, MSG3
   INT 21H  
      PRINTN ""
  

   MOV AH, 09H
   LEA DX, MSG4
   INT 21H 
     
      PRINTN ""

   MOV AH, 09H
   LEA DX, MSG5
   INT 21H 
      PRINTN ""

   MOV AH, 09H
   LEA DX, MSG6
   INT 21H 
      PRINTN ""

   MOV AH, 09H
   LEA DX, MSG7
   INT 21H
      PRINTN ""

   MOV AH, 09H
   LEA DX, MSG8
   INT 21H  
      PRINTN ""


   MOV AH, 09H
   LEA DX, MSG9
   INT 21H 
      PRINTN ""


    MOV AH, 09H
   LEA DX, MSG10
   INT 21H
      PRINTN ""
      
   RET 
   
   
   
CMPRESPCOLOROPC1:
   
   PRINTN ""
   PRINTN ""
   
   
   MOV AH, 09H
   LEA DX, MSG06
   INT 21H  
   
   MOV AH,01
   INT 21H
   SUB AL,30H
   MOV RESPUESTA2, AL
                      
    CMP RESPUESTA2, 1            
    JE CALL MODO1
   
    CMP RESPUESTA2, 2
    JE CALL MODO2
    
    CMP RESPUESTA2, 3
    JE CALL MODO3

    CMP RESPUESTA2, 4            
    JE CALL MODO4
   
    CMP RESPUESTA2, 5
    JE CALL MODO5
    
    CMP RESPUESTA2, 6
    JE CALL MODO6

    CMP RESPUESTA2, 7            
    JE CALL MODO7
   
    CMP RESPUESTA2, 8
    JE CALL MODO8
    
    CMP RESPUESTA2, 9
    JE CALL MODO9

    CMP RESPUESTA2, 0
    JE CALL MODO0
    
    
CMPRESPCOLOROPC2:
   
   PRINTN ""
   PRINTN ""
   
   
   MOV AH, 09H
   LEA DX, MSG06
   INT 21H  
   
   MOV AH,01
   INT 21H
   SUB AL,30H
   MOV RESPUESTA2, AL
                      
    CMP RESPUESTA2, 1            
    JE CALL MODO11
   
    CMP RESPUESTA2, 2
    JE CALL MODO22
    
    CMP RESPUESTA2, 3
    JE CALL MODO33

    CMP RESPUESTA2, 4            
    JE CALL MODO44
   
    CMP RESPUESTA2, 5
    JE CALL MODO55
    
    CMP RESPUESTA2, 6
    JE CALL MODO66

    CMP RESPUESTA2, 7            
    JE CALL MODO77
   
    CMP RESPUESTA2, 8
    JE CALL MODO88
    
    CMP RESPUESTA2, 9
    JE CALL MODO99

    CMP RESPUESTA2, 0
    JE CALL MODO00  
    
    
CMPRESPCOLOROPC3:
   
   PRINTN ""
   PRINTN ""
   
   
   MOV AH, 09H
   LEA DX, MSG06
   INT 21H  
   
   MOV AH,01
   INT 21H
   SUB AL,30H
   MOV RESPUESTA2, AL 
   
                      
    CMP RESPUESTA2, 1            
    JE CALL MODO111
   
    CMP RESPUESTA2, 2
    JE CALL MODO222
    
    CMP RESPUESTA2, 3
    JE CALL MODO333

    CMP RESPUESTA2, 4            
    JE CALL MODO444
   
    CMP RESPUESTA2, 5
    JE CALL MODO555
    
    CMP RESPUESTA2, 6
    JE CALL MODO666

    CMP RESPUESTA2, 7            
    JE CALL MODO777
   
    CMP RESPUESTA2, 8
    JE CALL MODO888
        
    CMP RESPUESTA2, 9
    JE CALL MODO999 
    
    CMP RESPUESTA2, 0
    JE CALL MODO00

    CMP RESPUESTA, 0            
    JE CALL MENU
    
MODO0:            ;VERDE CLARO
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H 
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 0AH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
   
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
   
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO1:            ;AZUL
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H 
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H  
    
    MOV AX, 0600H
    MOV BH, 01H      ;1 COLOR AZUL, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
  
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   
   MOV AH,0H    ; ESPERA QUE SE PRESIONE CUALQUIER TECLA PARA CONTINUAR
   INT 16H 
   
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    
   CALL MENU 
   
MODO2:            ;VERDE
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H 
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 02H      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
   
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
   
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO3:            ;CYAN
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H 
    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
   MOV AX, 0600H
   MOV BH, 03H      ;3 COLOR CYAN, 0 COLOR DE LETRA NEGRO
   MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
   MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
   INT 10H
   
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
   
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
   CALL MENU 
   
MODO4:            ;ROJO
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H  
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 04H      ;4 COLOR ROJO, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
    
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO5:            ;MAGENTA
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 05H      ;5 COLOR MAGENTA, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
    
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO6:            ;CAFE
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 06H      ;6 COLOR CAFE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
    
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO7:            ;GRIS CLARO
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 07H      ;7 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO8:            ;GRIS OSCURO
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 08H      ;8 COLOR ROJO, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     
   CALL MENU 
    
MODO9:            ;GRIS CLARO
    MOV AL,00H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H     
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 09H      ;7 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H 
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
    MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU
    
MODO00:            ;VERDE CLARO
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H 
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 0AH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
   
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
          
        MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU  

MODO11:            ;AZUL
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H 
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 01H      ;1 COLOR AZUL, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
        MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO22:            ;VERDE
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H  
        
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 02H      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
        MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO33:            ;CYAN
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H      
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 03H      ;3 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H 
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO44:            ;ROJO
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 04H      ;4 COLOR ROJO, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H 
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO55:            ;MAGENTA
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 05H      ;5 COLOR MAGENTA, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H 
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO66:            ;CAFE
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 06H      ;6 COLOR CAFE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO77:            ;GRIS CLARO
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H     
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 07H      ;7 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H   
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO88:            ;GRIS OSCURO
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H     
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 08H      ;8 COLOR ROJO, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
     PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
   
    
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
        MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO99:            ;GRIS CLARO
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H    
          
   PRINTN ""
   PRINTN "" 
   
   LEA DX,MENSAJE4
   MOV AH,09
   INT 21H     
   
   MOV AH,0AH
   LEA DX,RESPUESTA3
   INT 21H 
    
    MOV AX, 0600H
    MOV BH, 09H      ;7 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H 
   PRINTN ""
   PRINTN ""
   
   LEA DX,MSG11
   MOV AH,09
   INT 21H
   
   PRINTN ""
   PRINTN ""   
 
   LEA DX,RESPUESTA3
   MOV AH,09
   INT 21H 
   MOV AH,0H
   INT 16H
   
       MOV AX, 0600H
    MOV BH, 0FH      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    
   CALL MENU
    
MODO111:            ;AZUL
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 10H      ;1 COLOR AZUL, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO222:            ;VERDE
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 20H      ;2 COLOR VERDE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO333:            ;CYAN
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 30H      ;3 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO444:            ;ROJO
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 40H      ;4 COLOR ROJO, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO555:            ;MAGENTA
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 50H      ;5 COLOR MAGENTA, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO666:            ;CAFE
    MOV AL,03H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 60H      ;6 COLOR CAFE, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO777:            ;GRIS CLARO
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 70H      ;7 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
   
MODO888:            ;GRIS OSCURO
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 80H      ;8 COLOR ROJO, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H
    
    CALL MENU 
    
MODO999:            ;GRIS CLARO
    MOV AL,13H  ;CONFIGURACION PANTALLA
    MOV AH,0
    INT 10H
    
    MOV AX, 0600H
    MOV BH, 90H      ;7 COLOR CYAN, 0 COLOR DE LETRA NEGRO
    MOV CX, 0000H    ;ESQUINA SUPERIOR IZQUIERDA REN, COL
    MOV DX, 184FH    ;ESQUINA INFERIR DERECHA REN, COL
    INT 10H 
    
  ENDS






