
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 08 11:42:35 CST 2021
//----------------------------------------------------

package ensambladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Pseudoinstruccion = 20;
  public static final int Pseudoinstruccion_C_S = 16;
  public static final int Constante_Numerica_D = 10;
  public static final int Numero = 24;
  public static final int Pseudoinstruccion_W = 18;
  public static final int Simbolo = 21;
  public static final int Pseudoinstruccion_Dup_H = 9;
  public static final int Constante_Caracter_CS = 12;
  public static final int Pseudoinstruccion_Dup_D = 7;
  public static final int ERROR = 26;
  public static final int Instruccion = 22;
  public static final int Pseudoinstruccion_D_W = 5;
  public static final int Pseudoinstruccion_E = 19;
  public static final int Constante_Caracter_CD = 13;
  public static final int PseudoInsInco = 4;
  public static final int Registro = 23;
  public static final int EOF = 0;
  public static final int Pseudoinstruccion_D_S = 15;
  public static final int Pseudoinstruccion_B = 17;
  public static final int Linea = 25;
  public static final int Pseudoinstruccion_Dup_0 = 6;
  public static final int error = 1;
  public static final int Variable = 3;
  public static final int Pseudoinstruccion_S_S = 14;
  public static final int Pseudoinstruccion_Dup_Caracter = 8;
  public static final int Pseudoinstruccion_D_B = 2;
  public static final int Constante_Numerica_H = 11;
}

