
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 23 23:46:27 CDT 2021
//----------------------------------------------------

package ensambladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Pseudoinstruccion = 18;
  public static final int Pseudoinstruccion_C_S = 14;
  public static final int Constante_Numerica_D = 8;
  public static final int Pseudoinstruccion_W = 16;
  public static final int Simbolo = 19;
  public static final int Pseudoinstruccion_Dup_H = 7;
  public static final int Constante_Caracter_CS = 10;
  public static final int Pseudoinstruccion_Dup_D = 5;
  public static final int ERROR = 24;
  public static final int Instruccion = 21;
  public static final int Pseudoinstruccion_D_W = 3;
  public static final int Pseudoinstruccion_E = 17;
  public static final int Constante_Caracter_CD = 11;
  public static final int Registro = 22;
  public static final int EOF = 0;
  public static final int Pseudoinstruccion_D_S = 13;
  public static final int Pseudoinstruccion_B = 15;
  public static final int Linea = 23;
  public static final int Pseudoinstruccion_Dup_0 = 4;
  public static final int error = 1;
  public static final int Variable = 20;
  public static final int Pseudoinstruccion_S_S = 12;
  public static final int Pseudoinstruccion_Dup_Caracter = 6;
  public static final int Pseudoinstruccion_D_B = 2;
  public static final int Constante_Numerica_H = 9;
}

