
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 09 23:44:44 CST 2021
//----------------------------------------------------

package analisadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Pseudoinstruccion_C_S = 18;
  public static final int Pseudoinstruccion = 3;
  public static final int Constante_Numerica_D = 12;
  public static final int Numero = 28;
  public static final int Pseudoinstruccion_W = 8;
  public static final int Simbolo = 2;
  public static final int Interrupcion = 23;
  public static final int Pseudoinstruccion_Dup_H = 11;
  public static final int Constante_Caracter_CS = 14;
  public static final int Pseudoinstruccion_Dup_D = 9;
  public static final int ERROR = 4;
  public static final int Correcta = 26;
  public static final int PseudoinstruccionInc = 7;
  public static final int Instruccion = 22;
  public static final int Pseudoinstruccion_D_W = 20;
  public static final int ConstanteCadInc = 25;
  public static final int Pseudoinstruccion_E = 21;
  public static final int Constante_Caracter_CD = 15;
  public static final int Pseudoinstruccion_D_S = 17;
  public static final int Registro = 5;
  public static final int EOF = 0;
  public static final int Incorrecta = 27;
  public static final int Pseudoinstruccion_Dup_0 = 6;
  public static final int error = 1;
  public static final int Pseudoinstruccion_S_S = 16;
  public static final int Pseudoinstruccion_Dup_Caracter = 10;
  public static final int Pseudoinstruccion_D_B = 19;
  public static final int Constante_Numerica_H = 13;
  public static final int Sregistro = 24;
}

