
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 04 01:49:31 CST 2021
//----------------------------------------------------

package ensambladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IIO = 2;
  public static final int ERROR = 9;
  public static final int Instruccion_0 = 5;
  public static final int EOF = 0;
  public static final int IIE = 3;
  public static final int Instruccion_E = 6;
  public static final int Instruccion = 4;
  public static final int error = 1;
  public static final int Simbolo = 7;
  public static final int NoIdentificado = 8;
}

