/* The following code was generated by JFlex 1.4.3 on 29/11/21 10:09 PM */

package Proyecto;
import static Proyecto.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 29/11/21 10:09 PM from the specification file
 * <tt>C:/Users/danie/OneDrive/Documentos/5ª SEMESTRE FACULTAD/ENSAMBLADORES/Ensambladores/src/Proyecto/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\40\2\0\1\11\22\0\1\43\1\0\1\52\4\0"+
    "\1\51\1\33\1\34\1\0\1\10\1\41\1\10\2\0\1\4\1\2"+
    "\10\6\1\42\1\37\5\0\1\20\1\3\1\12\1\14\1\32\1\5"+
    "\1\44\1\7\1\31\1\26\1\45\1\23\1\24\1\27\1\22\1\15"+
    "\1\46\1\50\1\17\1\21\1\16\1\25\1\13\1\30\1\47\1\1"+
    "\1\35\1\0\1\36\1\0\1\1\uffa0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\2\3\1\1\1\4"+
    "\12\2\1\5\1\6\1\7\1\10\1\4\1\11\1\12"+
    "\1\13\2\1\1\3\1\14\1\2\2\3\1\0\1\3"+
    "\2\0\4\2\1\15\10\2\1\16\3\2\15\0\1\3"+
    "\1\0\1\3\1\2\2\0\11\2\2\0\1\2\2\0"+
    "\1\2\1\16\2\2\1\14\20\0\1\15\12\0\2\15"+
    "\1\0\2\15\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u0102"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a"+
    "\0\u0285\0\u02b0\0\u02db\0\u0306\0\53\0\u0331\0\53\0\u035c"+
    "\0\53\0\53\0\53\0\u0387\0\u03b2\0\53\0\126\0\u03dd"+
    "\0\u0408\0\u0433\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df\0\u050a"+
    "\0\u0535\0\u0560\0\126\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637"+
    "\0\u0662\0\u068d\0\u06b8\0\126\0\u06e3\0\u070e\0\u0739\0\u0764"+
    "\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\u08bc"+
    "\0\u08e7\0\u0912\0\u093d\0\u0387\0\u0387\0\u03b2\0\u03b2\0\u0968"+
    "\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0"+
    "\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18"+
    "\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\53\0\u0cef\0\u0d1a\0\u0d45"+
    "\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d"+
    "\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74\0\53\0\u0f9f\0\u0fca"+
    "\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc\0\u10f7\0\u1122"+
    "\0\u0e47\0\u0e72\0\u114d\0\u0ef3\0\u0f1e\0\u1178\0\u11a3\0\u11ce"+
    "\0\u11f9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\3\1\7\1\3"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\3\1\16"+
    "\1\17\2\3\1\20\1\21\1\3\1\22\3\3\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\11\5\3\1\34\1\35\54\0\7\3\2\0\21\3"+
    "\11\0\5\3\4\0\1\4\1\36\1\4\1\0\1\7"+
    "\45\0\6\3\1\37\2\0\3\3\1\37\5\3\1\37"+
    "\4\3\1\37\2\3\11\0\3\3\1\40\1\3\4\0"+
    "\1\41\1\42\1\41\1\43\1\44\3\0\1\43\1\0"+
    "\1\43\3\0\1\43\11\0\1\43\22\0\1\7\1\0"+
    "\1\7\1\0\1\7\55\0\1\45\2\0\1\46\26\0"+
    "\1\45\10\0\2\3\1\47\3\3\1\37\2\0\1\3"+
    "\1\50\3\3\1\37\2\3\1\51\1\37\4\3\1\37"+
    "\2\3\11\0\5\3\3\0\7\3\2\0\10\3\1\52"+
    "\10\3\11\0\5\3\3\0\2\3\1\53\3\3\1\37"+
    "\2\0\1\3\1\53\3\3\1\37\1\54\2\3\1\37"+
    "\4\3\2\37\1\3\11\0\5\3\3\0\7\3\2\0"+
    "\4\3\1\55\14\3\11\0\4\3\1\56\3\0\7\3"+
    "\2\0\3\3\1\37\1\57\1\37\1\3\1\60\7\3"+
    "\1\37\1\3\11\0\5\3\3\0\6\3\1\37\2\0"+
    "\11\3\1\37\4\3\1\37\2\3\11\0\5\3\3\0"+
    "\7\3\2\0\2\3\1\61\16\3\11\0\5\3\3\0"+
    "\7\3\2\0\6\3\1\62\1\3\1\63\10\3\11\0"+
    "\5\3\3\0\7\3\2\0\6\3\1\64\6\3\1\65"+
    "\3\3\11\0\5\3\3\0\7\3\2\0\5\3\1\37"+
    "\7\3\1\66\3\3\11\0\2\3\1\67\2\3\5\0"+
    "\1\70\6\0\1\71\1\0\1\72\2\0\1\73\1\74"+
    "\11\0\1\75\23\0\1\76\6\0\1\77\1\0\1\100"+
    "\2\0\1\101\1\102\11\0\1\103\20\0\40\30\1\0"+
    "\12\30\40\104\1\0\10\104\1\105\1\104\40\106\1\0"+
    "\11\106\1\107\1\0\7\3\2\0\7\3\1\110\11\3"+
    "\11\0\5\3\4\0\1\41\1\42\1\41\1\43\1\44"+
    "\1\36\2\0\1\43\1\0\1\43\3\0\1\43\11\0"+
    "\1\43\22\0\5\43\1\36\2\0\1\43\1\0\1\43"+
    "\3\0\1\43\11\0\1\43\22\0\1\44\1\43\1\44"+
    "\1\43\1\44\1\36\2\0\1\43\1\0\1\43\3\0"+
    "\1\43\11\0\1\43\31\0\1\45\2\0\1\111\26\0"+
    "\1\45\25\0\1\112\35\0\7\3\2\0\1\3\1\64"+
    "\17\3\11\0\5\3\3\0\7\3\2\0\2\3\1\64"+
    "\16\3\11\0\5\3\3\0\7\3\2\0\2\3\1\113"+
    "\16\3\11\0\5\3\3\0\7\3\2\0\21\3\11\0"+
    "\4\3\1\114\3\0\7\3\2\0\7\3\1\115\11\3"+
    "\11\0\5\3\3\0\7\3\2\0\5\3\1\116\13\3"+
    "\11\0\5\3\3\0\7\3\2\0\10\3\1\117\10\3"+
    "\11\0\5\3\3\0\2\3\1\64\4\3\2\0\21\3"+
    "\11\0\5\3\3\0\7\3\2\0\6\3\1\120\1\3"+
    "\1\121\10\3\11\0\5\3\3\0\7\3\2\0\5\3"+
    "\1\64\13\3\11\0\5\3\3\0\7\3\2\0\1\122"+
    "\20\3\11\0\5\3\3\0\7\3\2\0\13\3\1\64"+
    "\5\3\11\0\5\3\3\0\7\3\2\0\1\64\2\3"+
    "\1\64\5\3\1\64\7\3\11\0\5\3\3\0\7\3"+
    "\2\0\2\3\1\123\16\3\11\0\5\3\3\0\7\3"+
    "\2\0\4\3\1\53\14\3\11\0\5\3\11\0\1\124"+
    "\5\0\1\124\5\0\1\124\4\0\1\124\31\0\1\124"+
    "\7\0\1\124\3\0\1\124\4\0\1\124\31\0\1\124"+
    "\7\0\1\124\3\0\1\124\4\0\2\124\36\0\1\124"+
    "\1\0\1\124\11\0\1\124\30\0\1\124\13\0\1\124"+
    "\4\0\1\124\41\0\1\124\42\0\1\125\5\0\1\125"+
    "\5\0\1\125\4\0\1\125\31\0\1\125\7\0\1\125"+
    "\3\0\1\125\4\0\1\125\31\0\1\125\7\0\1\125"+
    "\3\0\1\125\4\0\2\125\36\0\1\125\1\0\1\125"+
    "\11\0\1\125\30\0\1\125\13\0\1\125\4\0\1\125"+
    "\41\0\1\125\34\0\7\3\2\0\20\3\1\126\11\0"+
    "\5\3\20\0\1\127\51\0\1\130\36\0\7\3\2\0"+
    "\20\3\1\131\11\0\5\3\3\0\7\3\2\0\2\3"+
    "\1\126\16\3\11\0\5\3\3\0\7\3\2\0\6\3"+
    "\1\131\12\3\11\0\5\3\3\0\6\3\1\132\2\0"+
    "\21\3\11\0\5\3\3\0\7\3\2\0\1\53\20\3"+
    "\11\0\5\3\3\0\7\3\2\0\1\133\20\3\11\0"+
    "\5\3\3\0\7\3\2\0\5\3\1\47\13\3\11\0"+
    "\5\3\3\0\7\3\2\0\21\3\11\0\4\3\1\134"+
    "\3\0\7\3\2\0\3\3\1\53\1\3\1\53\4\3"+
    "\1\53\6\3\11\0\5\3\36\0\1\135\54\0\1\135"+
    "\15\0\7\3\2\0\21\3\10\0\1\136\5\3\17\0"+
    "\1\137\46\0\1\130\21\0\1\140\1\0\1\141\5\0"+
    "\1\130\10\0\7\3\2\0\21\3\10\0\1\142\5\3"+
    "\3\0\7\3\2\0\6\3\1\64\12\3\11\0\5\3"+
    "\3\0\7\3\2\0\21\3\11\0\1\3\1\131\3\3"+
    "\3\0\7\3\2\0\10\3\1\53\10\3\11\0\5\3"+
    "\17\0\1\143\46\0\1\137\23\0\1\141\5\0\1\137"+
    "\11\0\1\144\1\0\1\145\1\0\1\144\42\0\1\146"+
    "\1\147\2\0\1\150\1\0\1\151\1\0\1\150\42\0"+
    "\1\152\1\153\17\0\1\154\54\0\1\155\33\0\1\144"+
    "\1\0\1\144\1\0\1\144\25\0\1\156\20\0\1\157"+
    "\1\160\1\157\1\160\1\157\3\0\1\160\1\0\1\160"+
    "\3\0\1\160\11\0\1\160\1\0\1\156\16\0\40\146"+
    "\1\0\10\146\1\161\1\146\40\147\1\0\11\147\1\162"+
    "\2\0\1\150\1\0\1\150\1\0\1\150\27\0\1\156"+
    "\16\0\1\163\1\164\1\163\1\164\1\163\3\0\1\164"+
    "\1\0\1\164\3\0\1\164\11\0\1\164\3\0\1\156"+
    "\14\0\40\152\1\0\10\152\1\165\1\152\40\153\1\0"+
    "\11\153\1\166\32\0\1\167\70\0\1\156\4\0\1\157"+
    "\1\160\1\157\1\160\1\157\1\170\2\0\1\160\1\0"+
    "\1\160\3\0\1\160\11\0\1\160\1\0\1\156\20\0"+
    "\5\160\1\170\2\0\1\160\1\0\1\160\3\0\1\160"+
    "\11\0\1\160\20\0\34\146\1\171\3\146\1\0\10\146"+
    "\1\161\1\146\34\147\1\172\3\147\1\0\11\147\1\162"+
    "\2\0\1\163\1\164\1\163\1\164\1\163\1\173\2\0"+
    "\1\164\1\0\1\164\3\0\1\164\11\0\1\164\3\0"+
    "\1\156\16\0\5\164\1\173\2\0\1\164\1\0\1\164"+
    "\3\0\1\164\11\0\1\164\20\0\36\152\1\174\1\152"+
    "\1\0\10\152\1\165\1\152\36\153\1\175\1\153\1\0"+
    "\11\153\1\166\44\0\1\176\42\0\1\156\54\0\1\156"+
    "\40\0\1\177\60\0\1\200\47\0\1\201\44\0\1\156"+
    "\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4644];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\22\1\1\11\1\1\1\11\1\1\3\11"+
    "\2\1\1\11\4\1\1\0\1\1\2\0\21\1\15\0"+
    "\1\1\1\0\2\1\2\0\11\1\2\0\1\1\2\0"+
    "\4\1\1\11\20\0\1\11\12\0\2\1\1\0\2\1"+
    "\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String LexEnsamblador;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 112) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { LexEnsamblador = yytext(); return Variables;
          }
        case 15: break;
        case 7: 
          { LexEnsamblador = yytext(); return ParentesisCAbrir;
          }
        case 16: break;
        case 9: 
          { LexEnsamblador = yytext(); return SaltoLinea;
          }
        case 17: break;
        case 8: 
          { LexEnsamblador = yytext(); return ParentesisCCerrar;
          }
        case 18: break;
        case 6: 
          { LexEnsamblador = yytext(); return ParentesisCerrar;
          }
        case 19: break;
        case 14: 
          { LexEnsamblador = yytext(); return Instrucciones;
          }
        case 20: break;
        case 1: 
          { return ERROR;
          }
        case 21: break;
        case 12: 
          { LexEnsamblador = yytext(); return Registros;
          }
        case 22: break;
        case 5: 
          { LexEnsamblador = yytext(); return ParentesisAbrir;
          }
        case 23: break;
        case 13: 
          { LexEnsamblador = yytext(); return PseudoInstrucciones;
          }
        case 24: break;
        case 4: 
          { /*Ignore*/
          }
        case 25: break;
        case 11: 
          { LexEnsamblador = yytext(); return DoblePunto;
          }
        case 26: break;
        case 10: 
          { /*IGNORE*/
          }
        case 27: break;
        case 3: 
          { LexEnsamblador = yytext(); return Constantes;
          }
        case 28: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
