
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 29 22:09:35 CST 2021
//----------------------------------------------------

package Proyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dup = 49;
  public static final int ax = 14;
  public static final int pusha = 4;
  public static final int dx = 23;
  public static final int enteros = 57;
  public static final int dw = 45;
  public static final int macro = 50;
  public static final int ds = 32;
  public static final int equ = 46;
  public static final int coma = 34;
  public static final int al = 16;
  public static final int jump = 60;
  public static final int dl = 25;
  public static final int ah = 15;
  public static final int di = 27;
  public static final int ss = 30;
  public static final int dh = 24;
  public static final int parenCC = 39;
  public static final int sp = 28;
  public static final int cbw = 2;
  public static final int parenCA = 38;
  public static final int db = 44;
  public static final int si = 26;
  public static final int ja = 10;
  public static final int byteptr = 47;
  public static final int wordptr = 48;
  public static final int cx = 20;
  public static final int constanteInvalida = 64;
  public static final int stacksegment = 41;
  public static final int sub = 9;
  public static final int cs = 31;
  public static final int EOF = 0;
  public static final int proc = 52;
  public static final int stosw = 5;
  public static final int error = 1;
  public static final int cl = 22;
  public static final int ch = 21;
  public static final int jnp = 12;
  public static final int lds = 6;
  public static final int cwd = 3;
  public static final int jnl = 13;
  public static final int parenNC = 37;
  public static final int signos = 63;
  public static final int parenNA = 36;
  public static final int doblepunto = 35;
  public static final int variableGrande = 65;
  public static final int cadenacomillasdoble = 55;
  public static final int variable = 54;
  public static final int bx = 17;
  public static final int jnc = 11;
  public static final int push = 7;
  public static final int errorEnsamblador = 61;
  public static final int es = 33;
  public static final int bp = 29;
  public static final int etiquetas = 62;
  public static final int ends = 43;
  public static final int bl = 19;
  public static final int endp = 53;
  public static final int mov = 8;
  public static final int cadenacomillassimples = 56;
  public static final int bh = 18;
  public static final int noHexadecimales = 59;
  public static final int endm = 51;
  public static final int codesegment = 42;
  public static final int noBinarios = 58;
  public static final int datasegment = 40;
}

