
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 08 16:44:03 CDT 2021
//----------------------------------------------------

package ensambladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Pseudoinstruccion = 2;
  public static final int Constante_Binaria = 20;
  public static final int Parentesis_c = 13;
  public static final int Constante_Hexadecimal = 21;
  public static final int Parentesis_a = 12;
  public static final int Constante_Decimal = 19;
  public static final int Simbolo = 3;
  public static final int Corchete_c = 11;
  public static final int ERROR = 22;
  public static final int Corchete_a = 10;
  public static final int Comilla_Simple = 14;
  public static final int Identificador = 18;
  public static final int Constante = 17;
  public static final int Coma = 8;
  public static final int Instruccion = 4;
  public static final int EOF = 0;
  public static final int Registro = 5;
  public static final int Linea = 6;
  public static final int error = 1;
  public static final int Dos_Puntos = 9;
  public static final int Libreria = 7;
  public static final int Comilla_Doble = 15;
  public static final int Fin_Cadena = 16;
}

